# config.yaml
directories:
  output_dir: /home/yinchao/VQASynth/vqasynth_output

arguments:
  source_repo_id: remyxai/vqasynth_sample
  target_repo_name: vqasynth_sample_processed
  images: "image"
  include_tags: "Park,Street,Home,Office,Garden,Playground,Warehouse,Shop,Library,Classroom,Kitchen,Living Room,Bedroom,Bathroom,Garage,Balcony,Alley,Sidewalk,Field,Meadow,Tennis court,Driveway,Lobby,Workshop,Gym"
  exclude_tags: "Aerial Photography,Single Subject,Macro Photography,Microscopic Views,Drawings,Unrealistic CGI,Graphs,Charts,Icons,Logos,Text Overlays,Minimalist,Art,Portraits,Close-up shot,Flat Art,Abstract Paintings,Silhouettes,Monochrome Photography,Stock Photos"
  openai_key: ""

  # 数据集采样配置
  dataset_sampling:
    enabled: true                    # 是否启用采样
    sample_size: 1                  # 采样数量（从10个样本中取1个）
    sample_method: "first"          # 采样方法: "first", "random", "stratified"
    random_seed: 42                 # 随机种子（用于可重复的随机采样）


# 使用国内镜像源
huggingface:
  mirror: "https://hf-mirror.com"
  timeout: 60
